title: "Yu Xi Chau"
description: My professional website and blog
url: "https://yuxichau.github.io"
baseurl: "/yuxichau"
logo: "assets/images/logo.png" 


# Theme
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Author
author:
  name: "Yu Xi Chau"
  avatar: "/assets/images/bio-photo.png" # Optional
  bio: "I'm a Data Scientist, AI Engineer and AI Governance Speciailist. I work at the intersection of AI and data science, focusing on responsible AI practices and innovative solutions."
  location: "Hong Kong"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:your-email@example.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://yuxichau.github.io"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/yuxichau"


# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Include files/folders
include: ["_pages"]

# Pagination
paginate: 5
paginate_path: /page:num/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
      permalink: /posts/:title/
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Main navigation
navigation:
  main:
    - title: "Home"
      url: /
    - title: "Posts"
      url: /posts/
    - title: "About"
      url: /about/

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourusername"


permalink: /:categories/:year/:month/:day/:title/